export const TECH_STACK_ICONS = {
  React_JS: "reactjs",
  NEXT_JS: "nextjs",
  NEXT_JS2: "nextjs2",
  ANT_DESIGN: "antd",
  MATERIAL_UI: "materialui",
  BITBUCKET: "bitbucket",
  GO: "go",
  HTML5: "html5",
  JIRA: "jira",
  JS: "js",
  LINUX: "linux",
  MONGODB: "mongodb",
  MYSQL: "mysql",
  NPM: "npm",
  NPM2: "npm2",
  POSTGRESQL: "postgresql",
  GIT: "git",
  GITHUB: "github",
  NODEJS: "nodejs",
  POSTMAN: "postman",
  PYTHON: "python",
  REDUX: "redux",
  TYPESCRIPT: "typescript",
  VITEJS: "vitejs",
  VS_CODE: "vscode",
  ZOD: "zod",
};
