import MainPage from "@/components/main";
import Navbar from "@/components/navbar";
import PersonalProject from "@/components/personalProject";
import Skills from "@/components/skills";
import Works from "@/components/works";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bipul Dubey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainPage />
      <Skills />
      <Works />
      <PersonalProject />
    </>
  );
}
